### ISSUE TITLE
Black screen in Video PV

### ISSUE THREAD

**Issue by Vetheasas** [rakisaionji/FrankenToneArcade#2]
I just installed your mod with everything including the pv_db. Also, even the original pv such as senbonzakura has blackscreen whenever I play it. The audio is working though. Is there any way to fix this problem?

**Comment by Vetheasas** [comment]
There are some minor problems with PV lighting and mouth animation. PDA sometime crashes when playing the new PVs.

**Comment by maruyamajin** [comment]
you need to convert those videos into mp4 format and then change the name file inside pv_db.txt 

for an example you have a problem with zenbonsakura video, first u need to find the pv on the movie folder. and when you found the video (file name kinda like "pv_***.wmv") you need to convert the files into mp4. when you done converting, go to the pv_db.txt inside, you need to find the converted video name and change the format like pv_***.wmv  to  pv_***.mp4 make sure u dindt mess anything. close and safe and it should be working

**Comment by Vetheasas** [comment]
It works perfectly. Thanks😏

**Comment by rakisaionji** [comment]
Well, the video thing is as @maruyamajin said. You have to convert them if your system does not support it. Idk why there are lots of people having that problem. I am using Windows 10 LTSB and just need to re-encode them to WMV9 instead of VC-1 and it can work.

And for the desync and crashing problems, desync sometimes occurred when your frame-rate drop or there is a halt in the UI like when you dragging the game window while the pv is playing, it is either caused by your hardware and by PDA is not optimized well (the model motion keep playing while the halt command is sent to the GL.

Some stages really just crash the game so it cannot be ported (like Weekender Girl) and there are stages that compatible with PDA but has a large amount of vertex (like Erase or Zero) than can randomly crash your game due to poor memory management and limited memory space of 32-bit.

All those problems above is the reason why I said PDA is too outdated and is not valuable to mod. AFT has better support for newer OS and more updated but the AFT hoarders will never share it, no matter how much you ask.

**Comment by Vetheasas** [comment]
Oh I see. curse you AFT hoarders lol
Anyway, thank for your work. It's incredible. Btw, Do you think we can emulate the card? It quite annoying to reset everytime I'm perfecting a song.

**Comment by BINiPad1999** [comment]
Can anyone help me with the location of the diva_adv.wmv in the text pls ? I already converted to mp3 but don't know where to put

**Comment by Vetheasas** [comment]
The directory should be project diva arcade/rom/movies. Also, you need to convert the video to mp4 not mp3. Then, 
go to the rom folder
open pv_db
search and replace all of the wmv to mp4
save

**Comment by BINiPad1999** [comment]
Yes, mp4. I type that wrong. I already change every pv_XXX.wmv to mp4 and edit the pv_db.txt and the pv in game works. But the file in rom/movies/diva_adv.wmv, it's the opening of the game but couldn't find it anywhere in the pv_db.txt
And how can i change the name of the song in the selection screen ? I saw someone change the song name to english

**Comment by rakisaionji** [comment]
From @Cainan:
```
you don't need to reencode wmvs or use mp4s on PDA
you can just use an older WMVDECOD.DLL placed into SysWOW64
```
